dependencies:
  - python=3
  - pip:
    - numpy
    - cython
    - spacy
    - ipykernel
    - scipy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - partd
    - dill
    - toolz
    - bokeh
    - psutil
